# Scripts divers

### Générations d'identités factices

Aller sur https://fr.fakenamegenerator.com/order.php

In [3]:
import pandas as pd
from pandas import Series, DataFrame

data = pd.read_csv('data/FakeNameGenerator.com_1229a5eb.csv')

In [4]:
data.columns

Index(['Number', 'Gender', 'NameSet', 'GivenName', 'Surname', 'StreetAddress',
       'City', 'Company', 'Occupation', 'Age'],
      dtype='object')

In [5]:
[city for city in data['City'].unique()]

['VILLEFRANCHE-SUR-SAÔNE',
 'FONTENAY-AUX-ROSES',
 'MULHOUSE',
 'LA PLAINE-SAINT-DENIS',
 'DUNKERQUE',
 'ATHIS-MONS',
 'SAINTES',
 'STRASBOURG',
 'FORT-DE-FRANCE',
 'BORDEAUX',
 'PARIS',
 'ISTRES',
 'COMBS-LA-VILLE',
 'ORANGE',
 'REZÉ',
 'ROANNE',
 'SAINTE-FOY-LÈS-LYON',
 'GAP',
 'BRON',
 'SAINT-BRIEUC',
 'POINTE-À-PITRE',
 'LE LAMENTIN',
 "VILLENEUVE-D'ASCQ",
 'TORCY',
 'MONTAUBAN',
 'TOULOUSE',
 'MILLAU',
 'LIBOURNE',
 'AJACCIO',
 'CERGY',
 'VILLEPARISIS',
 'VITRY-SUR-SEINE',
 'LA GARDE',
 'LA COURNEUVE',
 'LE CHESNAY',
 'SAINT-DENIS',
 'NANTES',
 'SAINT-LEU',
 'COUDEKERQUE-BRANCHE',
 'MÉRIGNAC',
 'COURBEVOIE',
 'PÉRIGUEUX',
 'MONTLUÇON',
 'GENNEVILLIERS',
 'SAINTE-GENEVIÈVE-DES-BOIS',
 'MONT-SAINT-AIGNAN',
 'ÉCHIROLLES',
 'REIMS',
 'LUNÉVILLE',
 'PUTEAUX',
 'DOLE',
 'ROUBAIX',
 'NOISY-LE-SEC',
 'MONTGERON',
 'DREUX',
 'AUXERRE',
 'MELUN',
 'ORVAULT',
 'WATTRELOS',
 'ROUEN',
 'DOUAI',
 'MARSEILLE',
 'OZOIR-LA-FERRIÈRE',
 'CONCARNEAU',
 'GARGES-LÈS-GONESSE',
 'LA MADELEINE',
 'ALFORTVILLE',
 'BOBIGNY',
 'BOURGOIN-JALLIEU',
 'SAINT-QUENTIN',
 'ÉPINAY-SUR-SEINE',
 'METZ',
 'PESSAC',
 'LYON',
 'VILLIERS-SUR-MARNE',
 'VAULX-EN-VELIN',
 'MANOSQUE',
 'LILLE',
 'PANTIN',
 'MONTPELLIER',
 'LOMME',
 'TOURS',
 'NICE',
 'POISSY',
 'CREIL',
 'THIAIS',
 'CHÂTELLERAULT',
 'SAINT-BENOÎT',
 'SAINT-LOUIS',
 'DEUIL-LA-BARRE',
 'ÉLANCOURT',
 'BOULOGNE-BILLANCOURT',
 'MAMOUDZOU',
 'MIRAMAS',
 'GOUSSAINVILLE',
 'CONFLANS-SAINTE-HONORINE',
 'NOGENT-SUR-MARNE',
 'GRENOBLE',
 'BAYONNE',
 'CACHAN',
 'BÉZIERS',
 'MAGAGNOSC',
 'LE GRAND-QUEVILLY',
 'COLOMBES',
 'RILLIEUX-LA-PAPE',
 'BÈGLES',
 'VILLEJUIF',
 'VALENCE',
 'FRESNES',
 'VICHY',
 'AMIENS',
 'MONTIGNY-LE-BRETONNEUX',
 'QUIMPER',
 'CHOLET',
 'LONS-LE-SAUNIER',
 'LEVALLOIS-PERRET',
 'GRADIGNAN',
 'CHAMPS-SUR-MARNE',
 'MENTON',
 'EAUBONNE',
 'NANCY',
 'LE ROBERT',
 'BEAUVAIS',
 'SAINT-MALO',
 'ÉVREUX',
 'LE HAVRE',
 'NÎMES',
 'AUCH',
 'NARBONNE',
 'LE PUY-EN-VELAY',
 'MANTES-LA-JOLIE',
 'HYÈRES',
 'BOURG-EN-BRESSE',
 'SAINT-LÔ',
 'LES ABYMES',
 'DENAIN',
 'LA TESTE-DE-BUCH',
 'CLERMONT-FERRAND',
 'SAINTE-MARIE',
 'BOIS-COLOMBES',
 'RAMBOUILLET',
 'ROCHEFORT',
 'TROYES',
 'VERTOU',
 'CHERBOURG',
 'AULNAY-SOUS-BOIS',
 'CAMBRAI',
 'VINCENNES',
 'TALENCE',
 'CHÂTEAUROUX',
 'CRÉTEIL',
 'ÉTAMPES',
 'LAON',
 'BESANÇON',
 'COLMAR',
 'DIGNE-LES-BAINS',
 'LA GARENNE-COLOMBES',
 'SAINT-PIERRE',
 'LORMONT',
 'SAINT-DIZIER',
 'CLICHY-SOUS-BOIS',
 'VILLENEUVE-SAINT-GEORGES',
 'VOIRON',
 'FRÉJUS',
 'CHATOU',
 'VILLEPINTE',
 'FRANCONVILLE-LA-GARENNE',
 'OLIVET',
 'COLOMIERS',
 'FÉCAMP',
 'SAINT-ANDRÉ',
 'MONS-EN-BAROEUL',
 "L'HAŸ-LES-ROSES",
 'SARCELLES',
 'SÈTE',
 'RIS-ORANGIS',
 'BRUNOY',
 'JUAN-LES-PINS',
 'TREMBLAY-EN-FRANCE',
 'ILLKIRCH-GRAFFENSTADEN',
 'CORBEIL-ESSONNES',
 'CHALON-SUR-SAÔNE',
 'ROSNY-SOUS-BOIS',
 'PONTAULT-COMBAULT',
 'MONTCEAU-LES-MINES',
 'SAINT-PAUL',
 'SARREGUEMINES',
 'SAINT-DIÉ',
 'CROIX',
 'MEUDON',
 'SAINT-ÉTIENNE',
 'DRAVEIL',
 'VÉLIZY-VILLACOUBLAY',
 'BIARRITZ',
 'AVIGNON',
 'RUEIL-MALMAISON',
 'FORBACH',
 'BRÉTIGNY-SUR-ORGE',
 'GIF-SUR-YVETTE',
 'GRANDE-SYNTHE',
 'HAGUENAU',
 'BAR-LE-DUC',
 'LAVAL',
 'LA SEYNE-SUR-MER',
 'BRIVE-LA-GAILLARDE',
 'CHÂLONS-EN-CHAMPAGNE',
 'ALBI',
 'DAX',
 'LA VARENNE-SAINT-HILAIRE',
 'MEYZIEU',
 'SAINT-JOSEPH',
 'SANNOIS',
 'MONTMORENCY',
 'DZAOUDZI',
 'VIGNEUX-SUR-SEINE',
 'BAGNEUX',
 'AGDE',
 'PIERREFITTE-SUR-SEINE',
 'TULLE',
 'MONT-DE-MARSAN',
 'VANVES',
 'CALUIRE-ET-CUIRE',
 "VILLENAVE-D'ORNON",
 'LE PERREUX-SUR-MARNE',
 'MAUBEUGE',
 'BRUAY-LA-BUISSIÈRE',
 'ISSY-LES-MOULINEAUX',
 'SAVIGNY-LE-TEMPLE',
 'SEVRAN',
 'LIMOGES',
 'ERMONT',
 'LE PLESSIS-ROBINSON',
 'GRIGNY',
 'HAZEBROUCK',
 'CARPENTRAS',
 'LE TAMPON',
 'AURILLAC',
 'STAINS',
 'LOOS',
 'CLAMART',
 'VESOUL',
 'PERPIGNAN',
 'LES MUREAUX',
 'SAINT-POL-SUR-MER',
 'SAUMUR',
 'MASSY',
 'AUBERVILLIERS',
 'TOURCOING',
 'SAVIGNY-SUR-ORGE',
 'TARBES',
 'ANGERS',
 'BASTIA',
 'CHARLEVILLE-MÉZIÈRES',
 'MEUDON-LA-FORÊT',
 'LANESTER',
 'MONTBÉLIARD',
 'SOTTEVILLE-LÈS-ROUEN',
 'MÂCON',
 'VALENCIENNES',
 'GUYANCOURT',
 'PRIVAS',
 'CAEN',
 'SAINT-SÉBASTIEN-SUR-LOIRE',
 'CASTRES',
 'BAGNOLET',
 'PAU',
 'ANTIBES',
 'TOULON',
 'SIX-FOURS-LES-PLAGES',
 'ALÈS',
 'SCHOELCHER',
 'HERBLAY',
 'CHELLES',
 'SAINT-LAURENT-DU-VAR',
 'ÉPINAL',
 'CLICHY',
 'NEVERS',
 'LA VALETTE-DU-VAR',
 'VILLENEUVE-SUR-LOT',
 'HÉROUVILLE-SAINT-CLAIR',
 'LUNEL',
 'LE BLANC-MESNIL',
 'LE PETIT-QUEVILLY',
 'SURESNES',
 'LIVRY-GARGAN',
 'LA POSSESSION',
 'BOURGES',
 'ORLY',
 'VITROLLES',
 'BONDY',
 'BÉTHUNE',
 'SAINT-PRIEST',
 'SALON-DE-PROVENCE',
 'DRAGUIGNAN',
 'VILLEMOMBLE',
 'VILLENEUVE-LA-GARENNE',
 'VANNES',
 'SAINT-CLOUD',
 'AIX-LES-BAINS',
 'SAINT-MARTIN',
 'BLAGNAC',
 'THIONVILLE',
 'PLAISIR',
 'VIENNE',
 'DÉCINES-CHARPIEU',
 'ANGLET',
 'MARCQ-EN-BAROEUL',
 'CAVAILLON',
 'CARCASSONNE',
 'BELFORT',
 'FONTAINE',
 'LISIEUX',
 'CAHORS',
 'DAMMARIE-LES-LYS',
 'POITIERS',
 'MURET',
 'ASNIÈRES-SUR-SEINE',
 'ANNEMASSE',
 'ABBEVILLE',
 'ÉVRY',
 'LE MANS',
 'MONTFERMEIL',
 'TRAPPES',
 'LE MÉE-SUR-SEINE',
 'OULLINS',
 'NEUILLY-SUR-MARNE',
 'ARGENTEUIL',
 'PONTOISE',
 'CHOISY-LE-ROI',
 'AIX-EN-PROVENCE',
 'SEDAN',
 'VALLAURIS',
 'CHARENTON-LE-PONT',
 'SAINT-HERBLAIN',
 'NOUMÉA',
 'SAINT-PIERRE-ET-MIQUELON',
 'CHAMBÉRY',
 'BAIE-MAHAULT',
 'DIEPPE',
 'ROMANS-SUR-ISÈRE',
 'SOISSONS',
 'HOUILLES',
 'VILLEURBANNE',
 'YERRES',
 'GAGNY',
 'SAINT-NAZAIRE',
 'ARRAS',
 'SENS',
 'LES ULIS',
 'VERDUN',
 'TAVERNY',
 'LE KREMLIN-BICÊTRE',
 'FLEURY-LES-AUBRAIS',
 'LONGJUMEAU',
 'BEZONS',
 'LORIENT',
 'RODEZ',
 'IVRY-SUR-SEINE',
 'MENDE',
 'VERNON',
 'JOUÉ-LÈS-TOURS',
 'RENNES',
 'ANNECY',
 'MONTÉLIMAR',
 'LA ROCHE-SUR-YON',
 'GONESSE',
 'SAINT-GERMAIN-EN-LAYE',
 'SAINT-MÉDARD-EN-JALLES',
 'CAYENNE',
 'MAISONS-LAFFITTE',
 'THONON-LES-BAINS',
 'SÈVRES',
 'CALAIS',
 'FONTENAY-SOUS-BOIS',
 'TOURNEFEUILLE',
 'OYONNAX',
 'VERSAILLES',
 'PALAISEAU',
 'SAINTE-ANNE',
 'NEUILLY-SUR-SEINE',
 'HÉNIN-BEAUMONT',
 'SAINT-OUEN',
 'SUCY-EN-BRIE',
 'VIERZON',
 'LIÉVIN',
 'VILLIERS-LE-BEL',
 'LE MOULE',
 'DRANCY',
 'ROMAINVILLE',
 'CHAMPIGNY-SUR-MARNE',
 'NANTERRE',
 'MONTREUIL',
 'BERGERAC',
 'LA ROCHELLE',
 'VIRY-CHÂTILLON',
 'MARTIGUES',
 'LE BOUSCAT',
 'LA CELLE-SAINT-CLOUD',
 'BEAUNE',
 'CANNES',
 'VÉNISSIEUX',
 'COGNAC',
 'SAINT-RAPHAËL',
 'ARLES',
 'LAMBERSART',
 'ORLÉANS',
 'LENS',
 'GRASSE',
 'MOULINS',
 'MEAUX',
 'SAINT-ÉTIENNE-DU-ROUVRAY',
 'CENON',
 'BASSE-TERRE',
 'MALAKOFF',
 'VANDOEUVRE-LÈS-NANCY',
 'CHAUMONT',
 'SAINT-MAUR-DES-FOSSÈS',
 'NIORT',
 'ANTONY',
 'LE PORT',
 'SAINT-CHAMOND',
 'MARIGNANE',
 'SARTROUVILLE',
 'MONTIGNY-LÈS-METZ',
 'LE CREUSOT',
 'BOULOGNE-SUR-MER',
 'FOIX',
 "SAINT-MARTIN-D'HÈRES",
 'LES LILAS',
 'FOUGÈRES',
 'MONTROUGE',
 'LE CANNET',
 'SAINT-MICHEL-SUR-ORGE',
 'CANNES-LA-BOCCA',
 'ALENÇON',
 'CHÂTENAY-MALABRY',
 'LA CIOTAT',
 'CAGNES-SUR-MER',
 'AUBAGNE',
 'MAISONS-ALFORT',
 'NOISY-LE-GRAND',
 'ARMENTIÈRES',
 'BREST',
 'GUÉRET',
 'AGEN',
 'ANGOULÊME',
 'COMPIÈGNE',
 'CHARTRES',
 'SCHILTIGHEIM',
 'CHÂTILLON']

In [6]:
data[data['City'] == 'SAUMUR']

,Number,Gender,NameSet,GivenName,Surname,StreetAddress,City,Company,Occupation,Age
394,395,male,French,Thomas,Salois,10 rue du Président Roosevelt,SAUMUR,Castle Realty,Blankbook binding worker,31
512,513,female,French,Jewel,Beauchesne,39 rue du Président Roosevelt,SAUMUR,Lionel Playworld,Employee training specialist,51
538,539,male,French,Gabriel,Coudert,58 rue du Président Roosevelt,SAUMUR,Office Warehouse,Fry cook,21
840,841,male,French,Alphonse,Cliche,12 rue du Président Roosevelt,SAUMUR,Landskip Yard Service,Stock clerk,36
863,864,male,French,Luc,Turgeon,58 rue du Président Roosevelt,SAUMUR,Incredible Universe,Set and exhibit designer,50
1008,1009,male,French,Isaac,Flamand,73 rue du Président Roosevelt,SAUMUR,Jack Lang,"Crushing, grinding, and polishing machine tender",29
1143,1144,male,French,Quincy,Lang,17 rue du Président Roosevelt,SAUMUR,Liberty Wealth Planner,Estimator,23
1426,1427,female,French,Aubrey,De La Ronde,47 rue du Président Roosevelt,SAUMUR,House Works,Ambulance driver,44
2200,2201,male,French,Brice,Cantin,47 rue du Président Roosevelt,SAUMUR,Hoyden,Applicator,44

In [7]:
data.groupby('Company').count().head()

,Number,Gender,NameSet,GivenName,Surname,StreetAddress,City,Occupation,Age
Company,,,,,,,,,
"10,000 Auto Parts",2,2,2,2,2,2,2,2,2
A Plus Lawn Care,4,4,4,4,4,4,4,4,4
A+ Electronics,1,1,1,1,1,1,1,1,1
A+ Investments,6,6,6,6,6,6,6,6,6
A. L. Price,5,5,5,5,5,5,5,5,5

In [8]:
data[data['Company'] == 'A Plus Lawn Care']

,Number,Gender,NameSet,GivenName,Surname,StreetAddress,City,Company,Occupation,Age
926,927,male,French,Gabriel,Joly,9 rue de Raymond Poincaré,NEUILLY-SUR-SEINE,A Plus Lawn Care,School social worker,54
1225,1226,male,French,Xarles,Fongemie,83 rue Saint Germain,GENNEVILLIERS,A Plus Lawn Care,Web writer,35
2236,2237,female,French,Suzette,Paradis,41 rue Sadi Carnot,AUCH,A Plus Lawn Care,Loan officer,44
2305,2306,male,French,Jeoffroi,Hébert,46 Place Napoléon,LAMBERSART,A Plus Lawn Care,Resort desk clerk,40

In [9]:
data.groupby('Occupation').count()

,Number,Gender,NameSet,GivenName,Surname,StreetAddress,City,Company,Age
Occupation,,,,,,,,,
911 operator,1,1,1,1,1,1,1,1,1
A & P mechanic,1,1,1,1,1,1,1,1,1
ABE teacher,1,1,1,1,1,1,1,1,1
ASE teacher,1,1,1,1,1,1,1,1,1
ATF agent,1,1,1,1,1,1,1,1,1
Abdominal sonographer,3,3,3,3,3,3,3,3,3
Abstractor,1,1,1,1,1,1,1,1,1
Academic dean,1,1,1,1,1,1,1,1,1
Account clerk,3,3,3,3,3,3,3,3,3
Account executive,1,1,1,1,1,1,1,1,1
Accountant,1,1,1,1,1,1,1,1,1
Accounts receivable clerk,3,3,3,3,3,3,3,3,3
Acoustical carpenter,1,1,1,1,1,1,1,1,1
Activity specialist,1,1,1,1,1,1,1,1,1
Addictions nurse,1,1,1,1,1,1,1,1,1
Adjudicator,2,2,2,2,2,2,2,2,2
Administrative assistant,2,2,2,2,2,2,2,2,2
Administrative assistant for human resource,2,2,2,2,2,2,2,2,2
Administrative clerk,1,1,1,1,1,1,1,1,1
Administrative lead,3,3,3,3,3,3,3,3,3
Administrative leader,1,1,1,1,1,1,1,1,1
Administrative manager,1,1,1,1,1,1,1,1,1
Administrative office manager,2,2,2,2,2,2,2,2,2
Administrative office specialist,2,2,2,2,2,2,2,2,2
Administrative specialist,1,1,1,1,1,1,1,1,1
Administrative supervisor,3,3,3,3,3,3,3,3,3
Administrative support manager,2,2,2,2,2,2,2,2,2
Administrative support services director,1,1,1,1,1,1,1,1,1
Administrative technician,1,1,1,1,1,1,1,1,1
Administrative worker supervisor,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...
Voice writer,1,1,1,1,1,1,1,1,1
Wait staff,1,1,1,1,1,1,1,1,1
Wastewater treatment plant and system operator,1,1,1,1,1,1,1,1,1
Water conservationist,2,2,2,2,2,2,2,2,2
Water transportation master,2,2,2,2,2,2,2,2,2
Water transportation mate,2,2,2,2,2,2,2,2,2
Water transportation pilot,1,1,1,1,1,1,1,1,1
Wealth manager,2,2,2,2,2,2,2,2,2
Weaving machine operator,1,1,1,1,1,1,1,1,1
Web designer,1,1,1,1,1,1,1,1,1
Web publications designer,1,1,1,1,1,1,1,1,1
Web writer,5,5,5,5,5,5,5,5,5
Welder,3,3,3,3,3,3,3,3,3
Welding machine tender,1,1,1,1,1,1,1,1,1
Welding worker,5,5,5,5,5,5,5,5,5
Wellhead pumper,1,1,1,1,1,1,1,1,1
Wildlife biologist,1,1,1,1,1,1,1,1,1
Wildlife officer,2,2,2,2,2,2,2,2,2
Winch operator,2,2,2,2,2,2,2,2,2
Wire installer,1,1,1,1,1,1,1,1,1
Woodworker,1,1,1,1,1,1,1,1,1
Woodworking machine tender,2,2,2,2,2,2,2,2,2
Word processor,3,3,3,3,3,3,3,3,3
Worker compensation coordinator,1,1,1,1,1,1,1,1,1
Workforce development specialist,3,3,3,3,3,3,3,3,3
"Wound, ostomy, and continence nurse",3,3,3,3,3,3,3,3,3
X-ray technician,1,1,1,1,1,1,1,1,1
Yardmaster,2,2,2,2,2,2,2,2,2
Yoga instructor,1,1,1,1,1,1,1,1,1
Zoologist,1,1,1,1,1,1,1,1,1

In [19]:
personnes = [{ "service": "Mécanique", "project": [], "name": "Madelene Cousteau"},
{ "service": "Electronique", "project": [], "name": "Arlette Bienvenue"},
{ "service": "Informatique", "project": [], "name": "Roxanne Brochu"},
{ "service": "Optique", "project": [], "name": "Jean Larson"},
{ "service": "Informatique", "project": [], "name": "Elizabeth Herman"},
{ "service": "Electronique", "project": [], "name": "Heloise Dubois"},
{ "service": "Electronique", "project": [], "name": "Darlene Herman"},
{ "service": "Mécanique", "project": [], "name": "Melodie Dubois"},
{ "service": "Optique", "project": [], "name": "Cosette Audet"},
{ "service": "Informatique", "project": [], "name": "Bruce Larson"},
{ "service": "Electronique", "project": [], "name": "Sophie Laforest"},
{ "service": "Informatique", "project": [], "name": "Lotye Cousteau"},
{ "service": "Electronique", "project": [], "name": "Josette Laforest"},
{ "service": "Informatique", "project": [], "name": "Vera Herman"},
{ "service": "Mécanique", "project": [], "name": "Albertine Desnoyers"},
{ "service": "Informatique", "project": [], "name": "Carine Laforest"},
{ "service": "Mécanique", "project": [], "name": "Matilda Audet"},
{ "service": "Mécanique", "project": [], "name": "Valérie Laforest"},
{ "service": "Informatique", "project": [], "name": "Noelle Dubois"},
{ "service": "Electronique", "project": [], "name": "Tracey Herman"},
{ "service": "Electronique", "project": [], "name": "Marphisa Brochu"},
{ "service": "Informatique", "project": [], "name": "Inès Cousteau"},
{ "service": "Electronique", "project": [], "name": "Agathe Desnoyers"},
{ "service": "Electronique", "project": [], "name": "Valentine Brochu"},
{ "service": "Informatique", "project": [], "name": "Andrée Laforest"},
{ "service": "Optique", "project": [], "name": "Mireille Audet"},
{ "service": "Electronique", "project": [], "name": "Jeanette Desnoyers"},
{ "service": "Optique", "project": [], "name": "Édith Audet"},
{ "service": "Mécanique", "project": [], "name": "Leone Bienvenue"}]

projects = ['Alpha', 'Cymbal', 'Tigre', 'Csw2000', 'Gringalet']

functions = ['chefDeProjet', 'developpeur', 'utilisateur','expert']

import random
import numpy as np

np_project = np.arange(len(projects))
np_function = np.arange(len(functions))

def randomize_nb_of_projects(projects) :
    return random.randint(0,len(projects)-1)

def randomize_project_and_function(nbProjects):
    projectChoice = np.random.choice(np_project, nbProjects, replace = False)
    functionChoice = np.random.choice(np_function, nbProjects, replace = False)
    
    project_selection = [projects[i] for i in projectChoice]
    function_selection = [functions[i] for i in functionChoice]
    
    return (project_selection, function_selection)
    
for p in personnes:
    
    nbProjects = randomize_nb_of_projects(projects)
    
    project_selection, function_selection = randomize_project_and_function(nbProjects)
    
    p['project'] = [ {"name": project_selection[i], "function" : function_selection[i]} 
                    for i in range(0,nbProjects)]
    
    print(p)

{'service': 'Mécanique', 'project': [], 'name': 'Madelene Cousteau'}
{'service': 'Electronique', 'project': [], 'name': 'Arlette Bienvenue'}
{'service': 'Informatique', 'project': [{'name': 'Cymbal', 'function': 'expert'}, {'name': 'Tigre', 'function': 'developpeur'}], 'name': 'Roxanne Brochu'}
{'service': 'Optique', 'project': [{'name': 'Cymbal', 'function': 'developpeur'}, {'name': 'Alpha', 'function': 'utilisateur'}, {'name': 'Csw2000', 'function': 'chefDeProjet'}], 'name': 'Jean Larson'}
{'service': 'Informatique', 'project': [{'name': 'Csw2000', 'function': 'developpeur'}, {'name': 'Cymbal', 'function': 'expert'}, {'name': 'Tigre', 'function': 'chefDeProjet'}], 'name': 'Elizabeth Herman'}
{'service': 'Electronique', 'project': [{'name': 'Csw2000', 'function': 'expert'}, {'name': 'Alpha', 'function': 'developpeur'}, {'name': 'Gringalet', 'function': 'chefDeProjet'}], 'name': 'Heloise Dubois'}
{'service': 'Electronique', 'project': [], 'name': 'Darlene Herman'}
{'service': 'Mécanique', 'project': [{'name': 'Cymbal', 'function': 'developpeur'}, {'name': 'Csw2000', 'function': 'expert'}, {'name': 'Tigre', 'function': 'chefDeProjet'}, {'name': 'Alpha', 'function': 'utilisateur'}], 'name': 'Melodie Dubois'}
{'service': 'Optique', 'project': [{'name': 'Tigre', 'function': 'utilisateur'}, {'name': 'Alpha', 'function': 'developpeur'}, {'name': 'Gringalet', 'function': 'expert'}], 'name': 'Cosette Audet'}
{'service': 'Informatique', 'project': [{'name': 'Alpha', 'function': 'expert'}, {'name': 'Csw2000', 'function': 'chefDeProjet'}, {'name': 'Tigre', 'function': 'utilisateur'}], 'name': 'Bruce Larson'}
{'service': 'Electronique', 'project': [{'name': 'Alpha', 'function': 'chefDeProjet'}, {'name': 'Gringalet', 'function': 'developpeur'}], 'name': 'Sophie Laforest'}
{'service': 'Informatique', 'project': [{'name': 'Tigre', 'function': 'chefDeProjet'}, {'name': 'Cymbal', 'function': 'developpeur'}, {'name': 'Csw2000', 'function': 'utilisateur'}, {'name': 'Alpha', 'function': 'expert'}], 'name': 'Lotye Cousteau'}
{'service': 'Electronique', 'project': [{'name': 'Tigre', 'function': 'chefDeProjet'}], 'name': 'Josette Laforest'}
{'service': 'Informatique', 'project': [{'name': 'Alpha', 'function': 'chefDeProjet'}, {'name': 'Gringalet', 'function': 'developpeur'}, {'name': 'Tigre', 'function': 'expert'}], 'name': 'Vera Herman'}
{'service': 'Mécanique', 'project': [{'name': 'Alpha', 'function': 'developpeur'}, {'name': 'Cymbal', 'function': 'utilisateur'}, {'name': 'Gringalet', 'function': 'expert'}, {'name': 'Tigre', 'function': 'chefDeProjet'}], 'name': 'Albertine Desnoyers'}
{'service': 'Informatique', 'project': [{'name': 'Alpha', 'function': 'utilisateur'}, {'name': 'Cymbal', 'function': 'chefDeProjet'}], 'name': 'Carine Laforest'}
{'service': 'Mécanique', 'project': [{'name': 'Csw2000', 'function': 'developpeur'}, {'name': 'Tigre', 'function': 'chefDeProjet'}], 'name': 'Matilda Audet'}
{'service': 'Mécanique', 'project': [{'name': 'Cymbal', 'function': 'utilisateur'}], 'name': 'Valérie Laforest'}
{'service': 'Informatique', 'project': [{'name': 'Cymbal', 'function': 'utilisateur'}, {'name': 'Tigre', 'function': 'developpeur'}, {'name': 'Gringalet', 'function': 'expert'}], 'name': 'Noelle Dubois'}
{'service': 'Electronique', 'project': [{'name': 'Cymbal', 'function': 'chefDeProjet'}], 'name': 'Tracey Herman'}
{'service': 'Electronique', 'project': [{'name': 'Tigre', 'function': 'expert'}, {'name': 'Cymbal', 'function': 'chefDeProjet'}, {'name': 'Csw2000', 'function': 'utilisateur'}, {'name': 'Gringalet', 'function': 'developpeur'}], 'name': 'Marphisa Brochu'}
{'service': 'Informatique', 'project': [{'name': 'Cymbal', 'function': 'chefDeProjet'}, {'name': 'Tigre', 'function': 'developpeur'}, {'name': 'Gringalet', 'function': 'expert'}], 'name': 'Inès Cousteau'}
{'service': 'Electronique', 'project': [{'name': 'Csw2000', 'function': 'utilisateur'}], 'name': 'Agathe Desnoyers'}
{'service': 'Electronique', 'project': [], 'name': 'Valentine Brochu'}
{'service': 'Informatique', 'project': [{'name': 'Gringalet', 'function': 'expert'}, {'name': 'Tigre', 'function': 'utilisateur'}, {'name': 'Csw2000', 'function': 'chefDeProjet'}, {'name': 'Cymbal', 'function': 'developpeur'}], 'name': 'Andrée Laforest'}
{'service': 'Optique', 'project': [{'name': 'Gringalet', 'function': 'chefDeProjet'}, {'name': 'Csw2000', 'function': 'utilisateur'}, {'name': 'Cymbal', 'function': 'developpeur'}, {'name': 'Tigre', 'function': 'expert'}], 'name': 'Mireille Audet'}
{'service': 'Electronique', 'project': [{'name': 'Cymbal', 'function': 'chefDeProjet'}, {'name': 'Alpha', 'function': 'utilisateur'}, {'name': 'Tigre', 'function': 'developpeur'}], 'name': 'Jeanette Desnoyers'}
{'service': 'Optique', 'project': [], 'name': 'Édith Audet'}
{'service': 'Mécanique', 'project': [{'name': 'Csw2000', 'function': 'expert'}], 'name': 'Leone Bienvenue'}